### ISSUE TITLE
Wire gauge calculations are incorrect

### ISSUE THREAD

**Issue by nareddyt** [wled-calculator/wled-calculator.github.io#2]
In the image below, the 2nd injection shows max current of `7.19 A` is greater than 3rd injection of max current `3.59 A`. But the min wire cross section is incorrect. Why is the wire with the greater current have a smaller `14 AWG` compared to the other one of `12 AWG`?

![image](https://user-images.githubusercontent.com/11142171/205538620-1c6f9535-8207-4a8e-b2b2-baedffad9c1c.png)

**Comment by wled-calculator** [comment]
Not only the current is considered in the calculation, but also the voltage drop. The third injection has longer wire, therefore it requires higher cross section to keep the voltage drop in range.

**Comment by nareddyt** [comment]
Thank you, makes much more sense
